# Generated by Django 3.0.3 on 2020-04-06 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewClient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100, verbose_name='Город')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('phone', models.CharField(max_length=100, verbose_name='Номер телефона')),
                ('message', models.CharField(max_length=100, verbose_name='Сообщение')),
                ('is_send', models.BooleanField(default=None, verbose_name='Отправлено в телеграм')),
                ('manager', models.CharField(max_length=100, verbose_name='Менеджер')),
                ('status', models.CharField(choices=[('OK', 'Договор заключен'), ('Think', 'Думает'), ('Decline', 'Отказ'), ('Another', 'Другое')], max_length=10)),
            ],
        ),
    ]
