# Generated by Django 3.0.3 on 2020-04-06 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newclient',
            name='manager',
            field=models.CharField(blank=True, max_length=100, verbose_name='Менеджер'),
        ),
        migrations.AlterField(
            model_name='newclient',
            name='message',
            field=models.CharField(blank=True, max_length=100, verbose_name='Сообщение'),
        ),
        migrations.AlterField(
            model_name='newclient',
            name='status',
            field=models.CharField(choices=[('OK', 'Договор заключен'), ('Think', 'Думает'), ('Decline', 'Отказ'), ('Another', 'Другое')], default='OK', max_length=10),
        ),
    ]
