# Generated by Django 3.0.3 on 2020-04-08 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_auto_20200406_1311'),
    ]

    operations = [
        migrations.AddField(
            model_name='newclient',
            name='message_id',
            field=models.IntegerField(blank=True, default=None, verbose_name='message id'),
        ),
        migrations.AlterField(
            model_name='newclient',
            name='status',
            field=models.CharField(blank=True, choices=[('OK', 'Договор заключен'), ('Think', 'Думает'), ('Decline', 'Отказ'), ('Passport', 'Ожидаем данные паспорта'), ('Another', 'Другое')], max_length=10),
        ),
    ]
