# Generated by Django 3.0.3 on 2020-03-02 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Router',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('router_name', models.CharField(max_length=50, unique=True, verbose_name='Имя роутера')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP-адрес')),
                ('admin_login', models.CharField(max_length=50, verbose_name='Логин для входа')),
                ('admin_password', models.CharField(blank=True, max_length=50, null=True, verbose_name='Пароль для входа')),
                ('available', models.BooleanField(default=False, verbose_name='Доступен')),
            ],
            options={
                'verbose_name': 'Роутер',
                'verbose_name_plural': 'Роутеры',
            },
        ),
    ]
